import './globals.css'
import NavBar from '../components/NavBar'
import Background from '@/components/Background'
import Footer from '@/components/Footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        {/* <Background/> */}
        {children}
        <Footer/>
        </body>
    </html>
  )
}
